version: "3.8"
services:
  shareit-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=shareit
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT-SERVER_URL=http://server:9090
  server:
    build: ./server
    ports:
      - "9090:9090"
    depends_on:
      - shareit-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shareit-db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=password

