CREATE TABLE IF NOT EXISTS ru.practicum.shareit.users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS ru.practicum.ru.practicum.shareit.requests (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                        description VARCHAR(512),
                                        created TIMESTAMP WITHOUT TIME ZONE,
                                        requestor_id BIGINT NOT NULL,
                                        FOREIGN KEY (requestor_id) REFERENCES ru.practicum.shareit.users (id)
);

CREATE TABLE IF NOT EXISTS ru.practicum.shareit.items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     description VARCHAR(512) NOT NULL,
                                     owner_id BIGINT NOT NULL,
                                     FOREIGN KEY (owner_id) REFERENCES ru.practicum.shareit.users (id),
                                     is_available BOOLEAN,
                                     request_id BIGINT,
                                     FOREIGN KEY (request_id) REFERENCES ru.practicum.ru.practicum.shareit.requests (id)
);

CREATE TABLE IF NOT EXISTS ru.practicum.shareit.bookings (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                        start_date TIMESTAMP WITHOUT TIME ZONE,
                                        end_date TIMESTAMP WITHOUT TIME ZONE,
                                        item_id BIGINT NOT NULL,
                                        FOREIGN KEY (item_id) REFERENCES ru.practicum.shareit.items (id),
                                        booker_id BIGINT NOT NULL,
                                        FOREIGN KEY (booker_id) REFERENCES ru.practicum.shareit.users (id),
                                        status VARCHAR(64)



);

CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                        text_comment VARCHAR(512),
                                        item_id BIGINT NOT NULL,
                                        FOREIGN KEY (item_id) REFERENCES ru.practicum.shareit.items (id),
                                        author_id BIGINT NOT NULL,
                                        FOREIGN KEY (author_id) REFERENCES ru.practicum.shareit.users (id),
                                        created TIMESTAMP WITHOUT TIME ZONE
);
